{% set name = "sonar-scanner-msbuild" %}
{% set version = "9.0.2.104486" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/SonarSource/sonar-scanner-msbuild/archive/{{ version }}.tar.gz
  sha256: c1440e62b56b47e4cb57bc8fbbe5d5cae5d0b7c65093d70703a92f43fd109def

build:
  noarch: generic
  number: 0

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

test:
  commands:
    - sonar-scanner-msbuild 2>&1 | grep -q "SonarScanner for MSBuild"

about:
  home: https://github.com/SonarSource/sonar-scanner-msbuild
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - license-files/
  summary: SonarScanner for .NET
  dev_url: https://github.com/SonarSource/sonar-scanner-msbuild

extra:
  recipe-maintainers:
    - danielnachun
