context:
  version: "11.3.0.1175"

package:
  name: sonar-scanner-msbuild
  version: ${{ version }}

source:
  url: https://github.com/SonarSource/sonar-scanner-msbuild/archive/${{ version }}.tar.gz
  sha256: c75b02b3ae3b14fa2aee0d5fae4315261c76ed0d83fe3ffb4f82d4640ae7ab32

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - "sonar-scanner-msbuild 2>&1 | grep -q \"SonarScanner for .NET\""

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - license-files/
  summary: SonarScanner for .NET
  homepage: https://github.com/SonarSource/sonar-scanner-msbuild
  repository: https://github.com/SonarSource/sonar-scanner-msbuild

extra:
  recipe-maintainers:
    - danielnachun
