context:
  version: "11.2.1.137242"

package:
  name: sonar-scanner-msbuild
  version: ${{ version }}

source:
  url: https://github.com/SonarSource/sonar-scanner-msbuild/archive/${{ version }}.tar.gz
  sha256: 8642be6729d6338e91c8b56fbb598b01fef7ede042c031eb520b23efdc7e7a6c

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - "sonar-scanner-msbuild 2>&1 | grep -q \"SonarScanner for .NET\""

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - license-files/
  summary: SonarScanner for .NET
  homepage: https://github.com/SonarSource/sonar-scanner-msbuild
  repository: https://github.com/SonarSource/sonar-scanner-msbuild

extra:
  recipe-maintainers:
    - danielnachun
