context:
  version: "11.2.0.135473"

package:
  name: sonar-scanner-msbuild
  version: ${{ version }}

source:
  url: https://github.com/SonarSource/sonar-scanner-msbuild/archive/${{ version }}.tar.gz
  sha256: 6ab087607157ed6bc84a409ab5e866fc6328e068c004aa8a9cafa38ddf8ecf68

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - "sonar-scanner-msbuild 2>&1 | grep -q \"SonarScanner for .NET\""

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - license-files/
  summary: SonarScanner for .NET
  homepage: https://github.com/SonarSource/sonar-scanner-msbuild
  repository: https://github.com/SonarSource/sonar-scanner-msbuild

extra:
  recipe-maintainers:
    - danielnachun
