context:
  version: "10.0.0.110776"

package:
  name: sonar-scanner-msbuild
  version: ${{ version }}

source:
  url: https://github.com/SonarSource/sonar-scanner-msbuild/archive/${{ version }}.tar.gz
  sha256: 8f78471654e8e8b35979bb132f8ac3f4193652408444e5c6654d0697a2d5148e

build:
  number: 0
  noarch: generic

requirements:
  host:
    - dotnet
    - nuget-license
    - sed
  run:
    - dotnet

tests:
  - script:
      - "sonar-scanner-msbuild 2>&1 | grep -q \"SonarScanner for MSBuild\""

about:
  license: GPL-3.0-or-later
  license_file:
    - LICENSE.txt
    - license-files/
  summary: SonarScanner for .NET
  homepage: https://github.com/SonarSource/sonar-scanner-msbuild
  repository: https://github.com/SonarSource/sonar-scanner-msbuild

extra:
  recipe-maintainers:
    - danielnachun
